#pragma once

enum class MessageType
{
    BEE_REGISTRATION = 0,
    BEE_ID_ASSIGNMENT,
    JOB_ASSIGNMENT,
    JOB_RESULT,
    STATUS_UPDATE,
    STATUS_CHECK,
    ERROR_REPORT,
    JOB_SUBMISSION,
    MONITOR_CONNECT,
    STATUS_SNAPSHOT,
    BENCHMARK_REQUEST,
    BENCHMARK_RESULT,
    COUNT
};
